### ISSUE TITLE
VidYen Fork

### ISSUE THREAD

**Issue by metallicats** [scala-network/MobileMiner#10]
Not an issue but a request.

Can you guys fork this so it would mine scala instead of monero?

https://github.com/VidYen/VidYen-WordPress-Plugins

**Comment by Mas7erMind** [comment]
Never heard about VidYen. What does the WP plugin does exactly?

**Comment by metallicats** [comment]
> Never heard about VidYen. What does the WP plugin does exactly?

It creates an internal wordpress points in wordpress, much like mycred. It gives points based on the amount of hashes you get from mining monero or altcoins in moneroocean pool. Unlike the usual javascript miners that are neglected by visitors cause it has no use to them, this one can be proactively be used by wp users since they can get points which can be exchanged by items in the site owners ecommerce shop.

Unfortunately the original author just passed away and no one continued on this project.

**Comment by ahmyi** [comment]
Closed as issue is unrelated
