### ISSUE TITLE
Raspberry

### ISSUE THREAD

**Issue by wendigo75** [scala-network/MobileMiner#11]
Rasp has Arm processor too it's possible to use for mining instead phones?
There is some fork for linux (Armhf?)

**Comment by SilentSeir** [comment]
Enable 64-bit 

Then download :  XLArig-v5.0.1-linux-arm64.zip

https://github.com/scala-network/XLArig/releases

**Comment by wendigo75** [comment]
Thank you to answer so quikly.

Excuse me if i’m not so anle/informed in mining and algos.

I like much your project and work and i have only 2 question (dubt):

  1.  Rasperry 32 bit (like pi3) are supported in mining?
  2.  There is possibility to direct Exchange your crypto?

I wish to explain better (excuse my english i’m italian):
I’ve tested in rasp-pi3+ Scrypt, SHA256, Cryptonote, Yespower Algorithms with success  but randomX cannot mine due to lack of memory (less than 2GB of RAM); having 2 pi3 i wish to mine your algo with it.

I’m mining YTN and wish to change crypto after last month but i’m having several issue to Exchange YTN in XMR or BTC: your vaule has a direct change future (i.e on changelly) or i will be forced to sell on market the total amount mined?

Thank u for response
Virgilio

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: SilentSeir<mailto:notifications@github.com>
Inviato: lunedì 11 maggio 2020 04:44
A: scala-network/MobileMiner<mailto:MobileMiner@noreply.github.com>
Cc: wendigo75<mailto:wendigo@hotmail.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [scala-network/MobileMiner] Raspberry (#11)


Enable 64-bit

Then download : XLArig-v5.0.1-linux-arm64.zip

https://github.com/scala-network/XLArig/releases

**Comment by SilentSeir** [comment]
32 bit will not work as far as I am aware and if you wish to exchange for other currencies the best way to do so as of right now would be to sell for Litecoin.

**Comment by wendigo75** [comment]
Thank you for support, compiled and tested on Raspberry pi3+:
It works around 8 H/s.
