### ISSUE TITLE
Are the hard coded IP's in use?

### ISSUE THREAD

**Issue by BKdilse** [scala-network/MobileMiner#14]
https://github.com/scala-network/MobileMiner/blob/57fa8f435fe8eecf4abe4a1eecbe3e2d644b9319/app/src/main/java/io/scalaproject/androidminer/api/ProviderManager.java#L114

Current correct address is "83.151.238.34".
v1.3.2 works fine, so I'm assuming the IP in the code is not used?

**Comment by Mas7erMind** [comment]
We use a dynamic IP address checker service API, we only use the hardcoded IP address as a backup. So no, they should not be used. I still changed the IP thought, just by precaution.
