### ISSUE TITLE
Wallet address incorrectly reported as wrong

### ISSUE THREAD

**Issue by Acethekangaroo** [scala-network/MobileMiner#15]
Hello I am trying to mine on herominers using the mobile miner using my address from the cli desktop wallet. on my desktop miner the address I use works fine on herominers, I have received payment and the pool accepts it but on the mobile miner it simply will not allow me to use the address no matter what pool I use.

**Comment by Mas7erMind** [comment]
What is the address you are using in the mobile miner?

**Comment by Acethekangaroo** [comment]
The address is Ssy29CsiTjQFkN8kncDCVKVrLsy73C2ELJpToRo6FXxh5yXDSm8Uuno5zdWAat5Efg3ggZWGi2izQLfqyZ2Xeh684Lt1nuEUnB

**Comment by ahmyi** [comment]
Issue fixed
