### ISSUE TITLE
Miner doesn't work for me.

### ISSUE THREAD

**Issue by Ojimi** [scala-network/MobileMiner#16]
I have tried the mobile miner on three different phones and get the same result. After putting in wallet address and pool and saving, I click start. The app acts like it wants to work, but just stops. Miner started pops up followed immediately by miner stopped. Uninstalled/reinstalled didn't help. Is there a minimum android version? Other settings outside of the app that I need to use?

**Comment by ahmyi** [comment]
Can we have your device details and miner version?

**Comment by Ojimi** [comment]
Samsung On5, android version 6.0.1. Samsung J3 Prime, android version 7.0. LG Zone 3, android version 5.1.1. Miner version is 1.3.2 on all 3. Same thing happens on all devices.

**Comment by ahmyi** [comment]
Can you give me screenshoots of the 3 devices

**Comment by Mercatronico** [comment]
I have the same problem with a 2 motorola moto G3

**Comment by ahmyi** [comment]
Can i have screenshots

**Comment by agung180310** [comment]
> Bisakah saya memiliki tangkapan layar

on Android I stopped because there was a statement "1GB PAGES UNAVAILABLE" what is the solution please solve it

**Comment by agung180310** [comment]
> Can i have screenshots

/storage/emulated/0/DCIM/Screenshots/Screenshot_2020-08-26-12-51-01-342_io.scalaproject.androidminer.jpg

**Comment by alex3s** [comment]
This happened to me on devices with less than 2GB memory. Probably the miner needs more than that to work.

**Comment by hayzamjs** [comment]
For support join our [discord](https://chat.scalaproject.io)
