### ISSUE TITLE
AMAYC: Cannot reach distant server

### ISSUE THREAD

**Issue by TurboCMD** [scala-network/MobileMiner#27]
When I start mining I have warning "AMAYC: Cannot reach distant server". HELP

**Comment by miguelv714** [comment]
Same here error -1

**Comment by miguelv714** [comment]
Also says invalid ip address

**Comment by hayzamjs** [comment]
Sometimes when the remote server goes down it shows this message, it can be ignored as the app reverts to manual temp control
