### ISSUE TITLE
Error -1

### ISSUE THREAD

**Issue by miguelv714** [scala-network/MobileMiner#29]
Invalid ip address used error

**Comment by miguelv714** [comment]
Motoz3 play

**Comment by ahmyi** [comment]
Which pool did you choose from?

**Comment by miguelv714** [comment]
> Which pool did you choose from?

Scala project

**Comment by Yella246** [comment]
I having the same issue with my Google pixel 3 how can I fix it

**Comment by hayzamjs** [comment]
Seems like a pool specific issue, please join [discord](https://chat.scalaproject.io) and get support there.
