### ISSUE TITLE
Add support for Exynos 9820

### ISSUE THREAD

**Issue by Tanju42** [scala-network/MobileMiner#30]
When I start mining on my Samsung Galaxy S10+ then it cant read the temparature of the chip and that results to an overheating phone.

Please add support for exynos chips

**Comment by niskala5570** [comment]
As far as I know, most mobile cpu dont have temperature sensor on it, instead it use battery temp.🤔

**Comment by Tanju42** [comment]
Exynos hast no cpu temp sensor
