### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by Shaneandrew304** [scala-network/MobileMiner#32]
Am only able to mine for maybe a hour or so and app crashes does not stay mining. I have double check all settings and everything.

**Comment by ahmyi** [comment]
What device are you using? Do u have amayc enabled? Try disabling amayc.

**Comment by shadowmx2** [comment]
Hi, i have crashes too. I use Motorola Moto G 8 Plus.

**Comment by Mas7erMind** [comment]
If you are able to mine for some time, then the app crashes when idle after a few hours, then it's probably Android killing the mining binaries. Check your phone settings to allow the app to run with no optimization in background.

**Comment by Shaneandrew304** [comment]
Mastamind I checked everything but will double check. Here is my device settings. 
![Uploading 20210207_164714.jpg…]()

**Comment by miguelv714** [comment]
I don't know what's wrong with my Moto z3 play the app gives me error 1 address not configured I believe

**Comment by Mas7erMind** [comment]
Can you go to About page and paste your Debug info here please?

**Comment by Shaneandrew304** [comment]
I think this is what you are looking for thank you sir.

**Comment by miguelv714** [comment]
> Can you go to About page and paste your Debug info here please?

Version Code: 9
Version Name: 1.3.5
Build Time: 04/09/2020 11:40 AM

Device Name: Motorola Moto Z3 Play
CPU Info: ABI: arm64-v8a
CPU_revision: 2
Processor: AArch64 Processor rev 4 (aarch64)
MSM_Hardware: SDM636 1.0 (2)
CPU_architecture: 8
Device: beckham
Radio: NA
processor: 7
BogoMIPS: 38.00
Serial: 0000000096442338
Revision: c000
CPU_part: 0x800
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU_implementer: 0x51
Hardware: Qualcomm Technologies, Inc SDM636
CPU_variant: 0xa

**Comment by Shaneandrew304** [comment]
I keep trying to post my debug info on here and it will not let me.. But I turned temp control off and it's been running for like 2 days straight.

**Comment by Mas7erMind** [comment]
We'll look into it. Thanks for the feedback.

**Comment by TannerSutherlin** [comment]
Yes, mine crashes too. I have a Samsung S10+. I have set it to never sleep but it still turns off and I have to go back in to start it again.

**Comment by Mas7erMind** [comment]
We have been working on an auto-restart process when it is aborted. Should be released very soon.

**Comment by Evox2008** [comment]
Have an old Galaxy S5 laying around mining, and crashing every couple of hours. I'll try to catch the debug report it generates and will paste it here once I have it.

Thanks!

**Comment by tsutherlin** [comment]
I've got two Motorolla G7 plus phones that crash every night although the Samsung S7 has been staying strong for over 5 days now.

**Comment by Mas7erMind** [comment]
Can you enable the "Send Debug information" option and send us the report?

**Comment by hayzamjs** [comment]
Closing for now since there's no response from user, re-open if need be
