### ISSUE TITLE
When shares become XLA?

### ISSUE THREAD

**Issue by DorinBila** [scala-network/MobileMiner#33]
When shares become XLA? I install Scala on phone and 3 or 4 times stop by self and force me to start again. And I want to know if that shares I can recover ?

**Comment by israel-p-s** [comment]
A share is not equivalent to Scala. A share is a participation for find a block.
When the pool where you are minning mines a block you will be paid by that block.
For example, if a block takes 100 shares to find and you contribute with 10 shares, then you will receive the (block reward)x(10/100).
The number of shares needed for fins a block is not statis, will fluctuate.

**Comment by DorinBila** [comment]
Hello Israel.

  I want ask you if can tell me how to transfer XLA from Scala Mining to Scala Valut? Or to guide me to learn how is work.

Thank you
Best Regards
  Dorin Cimpeanu
    Pe marți, 9 februarie 2021, 19:35:30 EET, Israel Palma Sebastià <notifications@github.com> a scris:  
 
 


A share is not equivalent to Scala. A share is a participation for find a block.
When the pool where you are minning mines a block you will be paid by that block.
For example, if a block takes 100 shares to find and you contribute with 10 shares, then you will receive the (block reward)x(10/100).
The number of shares needed for fins a block is not statis, will fluctuate.

**Comment by israel-p-s** [comment]
Hi!
Copy from Scala Vault your address and paste it in the minner. Then you only need to wait your pool mines a block. If you ask a more specific question, I can help you.
I suggest mine in my pool: PoolDeMineria.com
Regards :)
