### ISSUE TITLE
Scala Miner payout

### ISSUE THREAD

**Issue by TannerSutherlin** [scala-network/MobileMiner#36]
I have the miner set to payout at 10 but it hasn't paid anything out yet. I'm at 17.66 now.
![Screenshot_20210219-132558_Scala Miner](https://user-images.githubusercontent.com/77170397/108545707-22e55000-72b6-11eb-845a-4e0ec3a3efdd.jpg)

**Comment by richardwaifro** [comment]
You need to choose the right mining pool for payouts.

**Comment by Mas7erMind** [comment]
The payout amount needs to be set in the pool dashboard if you want to change the défaut minimum payout amount.

**Comment by TannerSutherlin** [comment]
Where would I find that? I changed it on the settings on the app already. I'm using the official pool mine.scalaproject.io

**Comment by Mas7erMind** [comment]
Go to https://pool.scalaproject.io/#worker_stats and click on Settings and edit Minimum payout

![image](https://user-images.githubusercontent.com/35771256/108554717-7f4e6c80-72c2-11eb-8d70-2b0965d951ff.png)

**Comment by TannerSutherlin** [comment]
Got it thanks! I appreciate the quick response!

**Comment by ahmyi** [comment]
FYI. Minimum payout for official pool is at 100XLA
