### ISSUE TITLE
cannot enter address

### ISSUE THREAD

**Issue by PSLLSP** [scala-network/MobileMiner#57]
SCALA miner 2.3.0 for Android

I try it with a tablet from Amazon (Fire 8 HD, 2018). I can mine to "donate address", it looks ok. Donate address is `SvkFLjR4DST5bAG8SSHWfta4MsCzRrDEPNx72cTetqcoPfkwi7cFA2sYGG2Tf51rQ9EMSPHVuzxeoS4Y7ieicg5A1M24A8TTW`, it is accepted.

When I try to change address in miner setting, my address is rejected with error **Invalid Wallet Address**, the error is printed when I try to SAVE new configuration. My XLA address was generated in SCALA desktop application. I assume there is a bug in Android SCALA miner, that form validation is not good... I paste my address from clipboard (camera for QR scan doesn't work, that is other issue).

If valid address is expected, it means **I cannot use username**; some pools use **username**, like mininingrigrentals. The validation of address should not be mandatory, miner can print warning that address is not valid but it should accept whatever...

My first try of this miner was that I started with predefined donation address. I was not able to replace it later with my address. I uninstalled the miner and installed it again. I tried to enter my address during initial setup but it was not accepted. I installed mobile wallet and used address that was generated in mobile wallet. It was accepted. I was able to replace this address with address that was created with desktop wallet later. Black magic... Anyway, expectation that address has to be valid is wrong, it could be username for mining pool...

**Comment by hayzamjs** [comment]
Cannot reproduce, please join our [discord](https://chat.scalaproject.io) for support.
