### ISSUE TITLE
What is modern Android device? Best Android device to run Scala miner??

### ISSUE THREAD

**Issue by PSLLSP** [scala-network/MobileMiner#58]
I tried to run Scala Android miner on several Android devices, on my phone, on my tablet, on my Android TV box and I tried to run it on RPI4 with LineageOS. I always receive message that my device architecture is old and hashrate will be low. And it is low, about 10 h/s, RPI4 can calculate about 18 H/s, it is the best Android device I have...

The key question is, what is modern Android device, what is expected? What CPU features are important for XLA miner?? Is size of RAM important? Are there any reference devices? Maybe you have a list with benchmarks for several Android devices...

I assume that size of RAM is not the key parameter; RPI4 with 4GB of RAM doesn't mine significantly faster than device with just 1.5GB of RAM...

BTW, miner that runs on device "My Phone" at [scalaproject.io](https://scalaproject.io/#mobileminer) reports avg 303.8 H/s and max 454,7 H/s. I am not sure if that is real device, it could be just a simulator...

There is a YouTube video about mobile scala miner at channel *Early Bird*, user runs 4/8 cores on device "Vivo Beast Phone", hashrate is about 180 H/s. It looks like a simulator running on PC.

**Comment by hayzamjs** [comment]
Please ask these kind of questions on our [discord](https://chat.scalaproject.io).
