### ISSUE TITLE
Miner worked fine but now it still bu i earn Notting over 2 days

### ISSUE THREAD

**Issue by rezor555** [scala-network/MobileMiner#62]
I have used the mobile miner for some time now and it worked fine 
But now it runs like normal but the last days i havent earn xla.. i do around 450 hash at 4 core and normal i do 850-1000hash at 7 core but earn no xla .. ?

**Comment by hayzamjs** [comment]
Doesn't seem like a miner issue more about the fact that the difficulty fluctuates leading to more or less income for the miner, join our [discord](https://chat.scalaproject.io) for more info.
